income: ["salary",
    "third",
    "freelance",
    "other",
    "interests",
    "virtual",
    "transfer_in"]
transport: ["metro",
    "cab",
    "bus",
    "gas",
    "toll",
    "parking"]
home: ["rent",
    "mortgage",
    "house",
    "furniture"]
utilities: ["EPM",
    "UNE",
    "cellphone",
    "cable",
    "laundry"]
food: ["groceries",
    "restaurant",
    "mecato",
    "licour"]
departmental: ["clothing",
    "books",
    "magazines",
    "apps",
    "hardware",
    "toys",
    "apps_subscriptions",
    "barber_shop",
    "personal_items"]
entertainment: ["movies",
    "sports",
    "theater",
    "stadium"]
medical: ["insurance",
    "medicines",
    "appointments"]
misc: ["air_tickets",
    "hotel",
    "gift",
    "other",
    "nonprofit_entity",
    "trip"]
bank: ["fee",
    "interests",
    "debit_note",
    "credit_note",
    "other"]
third: ["loan"]
transfer: ["credit_card",
    "cash",
    "inversion",
    "savings"]